# This is a basic workflow to help you get started with Actions

name: tep

# Controls when the workflow will run
on:
  push:
  schedule:
  # 定时任务，在每天的5点推送天气信息到邮箱
    - cron: '0 21 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: '测试项目'
        run: python ./test.py

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo '年号夫i然后辅热办公人员',
          echo '年号夫i然后辅热办公人员'.
