# This is a basic workflow to help you get started with Actions

name: tep

# Controls when the workflow will run
on:
  push:
  schedule:
  # 定时任务，在每天的5点推送天气信息到邮箱
    - cron: '0 21 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: '体温上传'
        env:
          NAME: ${{ secrets.NAME }}
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          QQ: ${{ secrets.QQ }}
         
        run: python ./main.py

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo '年号夫i然后辅热办公人员',
          echo '年号夫i然后辅热办公人员'.
